name: Daily run

on:
  schedule:
    - cron: "0 6 * * 1-5"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  watchdog:
    runs-on: ubuntu-latest
    steps:
      - name: Start watchdog checking job starts
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "watchdog.yml",
              ref: context.ref,
              inputs: {
                run_id: context.runId.toString()
              }
            })

  dagster-run:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run dagster
        run: |
          uv run dg launch --job daily_job --partition $(date --date="yesterday" '+%Y-%m-%d')
        env:
          DAGSTER_HOME: ${{ vars.dagster_home }}
          ENVIRONMENT: prd
          DATA_DIRECTORY_PRD: ${{ vars.data_directory }}
